[project]
name = "modrecco"
version = "0.1.0"
description = "Recommender System for NUS mods"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.5.1",
    "jupyterlab-vim>=4.1.4",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
]
